name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) - cc @$AUTHOR"
template: |
  ## What"s changed? 😳

  $CHANGES

categories:
  - title: "📜 Content"
    labels:
      - "content"
      - "netlify-cms/pending_publish"
  - title: "🚀 Features and Enhancements"
    labels:
      - "feature"
      - "enhancement"
      - "perf"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "hotfix"
  - title: "💖 General Changes"
    labels:
      - "patch"
      - "docs"
      - "test"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "maintenance"

autolabeler:
  - label: "bugfix"
    branch:
      - '/fix\/.+/'
    title:
      - '/\bfix\b(?![(]deps[)])/i'
  - label: "enhancement"
    branch:
      - '/feat\/.+/'
    title:
      - "/feat/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
      - '/style\/.+/'
      - '/refactor\/.+/'
    title:
      - "/chore/i"
      - "/style/i"
      - "/refactor/i"
  - label: "docs"
    branch:
      - '/docs\/.+/'
    title:
      - "/docs/i"
  - label: "skip-changelog"
    title:
      - "/merge/i"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "unbreaking"
  patch:
    labels:
      - "patch"
  default: patch

exclude-labels:
  - "skip-changelog"

change-title-escapes: '\<*_&' # Add # and @ to disable mentions, and ` to disable code blocks.

replacers:
  - search: '/(\w+(?:\(\w+\))?!?: )/g'
    replace: ""
