backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "content: added new {{collection}}"
    update: "content: update {{collection}}"
    delete: "content: remove {{collection}}"

media_folder: "static/img"
public_folder: "/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog-page/blogs"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    fields:
      - {
          label: "ContentPath",
          name: "contentpath",
          widget: "hidden",
          default: "blog",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Thumbnail Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - {
          label: "Thumbnail Tag",
          name: "alt",
          widget: "string",
          required: false,
        }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Blog Type",
          name: "type",
          widget: "select",
          options: ["News", "Event", "Announcement", "Article", "Message"],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "upcoming events"
    label: "Upcoming Events"
    folder: "content/blog-page/upcoming"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{event-name.fields}}"
    fields:
      - {
          label: "ContentPath",
          name: "contentpath",
          widget: "hidden",
          default: "events",
        }
      - { label: "Event Name", name: "event-name", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Created Date", name: "date", widget: "datetime" }
      - {
          label: "Scheduled Date(s)",
          name: "date-d",
          widget: "string",
          hint: "Example: '01-05'(Multi-day event) or '01' (Single-day event).",
        }
      - {
          label: "Scheduled Month",
          name: "date-m",
          widget: "string",
          hint: "Example: 'JAN-FEB'(Overlapped month) or 'JAN'.",
        }
      - {
          label: "Starting Time & End Time",
          name: "time",
          widget: "string",
          hint: "Example: 8:00am - 12:00pm",
        }

  - name: "featured blog"
    label: "Featured Blog"
    folder: "content/blog-page/featured"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    fields:
      - {
          label: "ContentPath",
          name: "contentpath",
          widget: "hidden",
          default: "featured",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Thumbnail Tag", name: "alt", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - {
          label: "Blog Type",
          name: "type",
          widget: "select",
          options: ["News", "Event", "Announcement", "Article", "Message"],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "homepage featured"
    label: "Homepage Featured"
    folder: "content/index-page/featured"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    fields:
      - {
          label: "ContentPath",
          name: "contentpath",
          widget: "hidden",
          default: "featured",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Thumbnail Tag", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
