name: CI

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main, qa]

jobs:
  stylecheck:
    name: Check for code style issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - run: yarn stylecheck
